In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib as plt
digits = load_digits()

In [85]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data , digits.target , test_size = 0.3)

In [86]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9592592592592593

In [87]:
svm = SVC(gamma='auto')
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.31666666666666665

In [88]:
rf = RandomForestClassifier(n_estimators= 40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [89]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [90]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [96]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)
    

In [104]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

scores_logistics = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_logistics.append(get_score(LogisticRegression(solver = 'liblinear', multi_class='ovr'), x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(gamma = 'auto'), x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators= 40), x_train,x_test,y_train,y_test))

In [107]:
scores_logistics

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [108]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [109]:
scores_rf

[0.9282136894824707, 0.9549248747913188, 0.9181969949916527]

In [110]:
from sklearn.model_selection import cross_val_score

In [112]:
cross_val_score(LogisticRegression(solver = 'liblinear', multi_class='ovr'), digits.data,digits.target, cv = 3)

array([0.89482471, 0.95325543, 0.90984975])

In [113]:
cross_val_score(SVC(gamma='auto'), digits.data,digits.target, cv = 3)

array([0.38063439, 0.41068447, 0.51252087])

In [114]:
cross_val_score(RandomForestClassifier(n_estimators= 40), digits.data,digits.target, cv = 3)

array([0.92320534, 0.95325543, 0.91819699])

In [125]:
score = cross_val_score(RandomForestClassifier(n_estimators= 10), digits.data,digits.target, cv = 3)
np.average(score)

0.9015025041736227

In [126]:
score2 = cross_val_score(RandomForestClassifier(n_estimators= 20), digits.data,digits.target, cv = 3)
np.average(score2)

0.9187534780189205

In [127]:
score3 = cross_val_score(RandomForestClassifier(n_estimators= 30), digits.data,digits.target, cv = 3)
np.average(score3)

0.9321090706733445

In [128]:
score3 = cross_val_score(RandomForestClassifier(n_estimators= 40), digits.data,digits.target, cv = 3)
np.average(score3)

0.9348914858096827